# Generated by Django 5.2.1 on 2025-05-11 20:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.CharField(blank=True, help_text='Book categories, e.g., Adventure | Dark fantasy', max_length=255),
        ),
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.TextField(default='   '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='image_url',
            field=models.URLField(blank=True, help_text='URL to the book cover image', max_length=500),
        ),
        migrations.AddField(
            model_name='book',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='borrowed_by',
            field=models.ForeignKey(blank=True, help_text='User who has borrowed the book, if any', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Users.user'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['title', 'author'], name='Users_book_title_7aa0e0_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['is_borrowed'], name='Users_book_is_borr_3c8488_idx'),
        ),
    ]
