# Generated by Django 5.2.1 on 2025-05-11 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_book_category_book_description_book_image_url_and_more'),
    ]

    operations = [
    ]
